version: "3.9"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"

  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ui:/app
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app
    depends_on:
      - mongo