version: "3.9"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=taxonDB
    volumes:
      - ./api/db/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
      - mongo-data:/data/db
      
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api/data:/app/data  # Ensure taxon data is mounted correctly
    environment:
      - MONGO_URI=mongodb://admin:example@mongo:27017/taxonDB?authSource=admin
      - MAIN_DIR=/app
    depends_on:
      - mongo

  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ui:/app
    environment:
      - VUE_APP_API_URL=http://localhost:5000
    depends_on:
      - api

volumes:
  mongo-data: